---
stages:
  - build
  - upload
  - add

build:
  stage: build
  script:
    - bazel build --keep_going //...
  tags:
    - k8s-mgit-bazel

upload:
  stage: upload
  script:
    - upload-deb --config upload-deb.yaml
  artifacts:
    paths:
      - deb-out/*
  only:
    refs:
      - master
  tags:
    - k8s-mgit-bazel

add:
  stage: add
  variables:
    GIT_STRATEGY: none
  script:
    - ~/upload-deb.py
  only:
    refs:
      - master
  after_script:
    - rm -r deb-out/
  needs:
    - job: upload
      artifacts: true
  tags:
    - mgit
    - pkg
