---
stages:
  - linter
  - build
  - upload
  - add

variables:
  GOLANGCI_LINT_VERSION: 'v1.56.2'
lint:
  image: golangci/golangci-lint:$GOLANGCI_LINT_VERSION
  stage: linter
  script:
    # Use default .golangci.yml file from the image if one is not present in the project root.
    - '[ -e .golangci.yml ] || cp /golangci/.golangci.yml .'
    - golangci-lint run

build:
  stage: build
  script:
    - bazel build --keep_going //...
  tags:
    - k8s-mgit-bazel

upload:
  stage: upload
  script:
    - upload-deb --config upload-deb.yaml
  artifacts:
    paths:
      - deb-out/*
  only:
    refs:
      - master
  tags:
    - k8s-mgit-bazel

add:
  stage: add
  variables:
    GIT_STRATEGY: none
  script:
    - ~/upload-deb.py
  only:
    refs:
      - master
  after_script:
    - rm -r deb-out/
  needs:
    - job: upload
      artifacts: true
  tags:
    - mgit
    - pkg
