linters:
  enable-all: true
  disable:
    - contextcheck
    - cyclop
    - depguard
    - err113
    - errorlint
    - exhaustruct
    - funlen # Function has too many statements
    - gocognit
    - gosec
    - lll
    - mnd # Exclude since the are used for e.g. context timeouts, buffer size, filemodes,...
    - musttag
    - nestif
    - nlreturn # return with no blank line before
    - perfsprint
    - tagliatelle # json(camel)
    - tenv # deprecated (since 1.64.0)
    - varnamelen
    - wrapcheck
    - wsl # assignments should only be cuddled with other assignments
