version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - embeddedstructfieldcheck
    - err113
    - errorlint
    - exhaustruct
    - funlen
    - goconst
    - gocognit
    - gosec
    - lll
    - mnd
    - modernize
    - musttag
    - nestif
    - nlreturn
    - noctx
    - noinlineerr
    - perfsprint
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
